import argparse
import subprocess
import os
import re
import sys

# Paths based on your WSL environment
spec_dir = os.path.expanduser("~/interplay/spec2017")
gem5_dir = os.path.expanduser("~/interplay/tageCS/gem5-tageassist")
gem5_opt = os.path.join(gem5_dir, "build/X86/gem5.fast")
se_py = os.path.join(gem5_dir, "configs/deprecated/example/se.py")

parser = argparse.ArgumentParser(description="Run SPEC benchmark via Gem5 SE mode")
parser.add_argument('--benchmark', required=True, help="e.g. 505.mcf_r")
parser.add_argument('--cpu-type', default="X86TimingSimpleCPU")
parser.add_argument('--bp-type', help="e.g. TAGE, LTAGE")

# Intercept instruction counts natively
parser.add_argument('--warmup-insts', type=str, help="Number of warmup instructions")
parser.add_argument('--maxinsts', type=str, help="Maximum instructions to execute")
parser.add_argument('--fast-forward', type=str, help="Number of instructions to fast forward")
parser.add_argument('--cmd-override', type=str, help="Use this binary instead of the SPEC exe (still uses SPEC inputs)")

args, unknown_args = parser.parse_known_args()

# Locate bench directory
bench_path = os.path.join(spec_dir, "benchspec", "CPU", args.benchmark)
run_dir = os.path.join(bench_path, "run")

if not os.path.exists(run_dir):
    print(f"Error: Run directory not found. Have you built {args.benchmark}?")
    sys.exit(1)

# Find the first run_base directory generated by runcpu (--action=setup)
run_base_dirs = [d for d in os.listdir(run_dir) if d.startswith("run_base_") and os.path.isdir(os.path.join(run_dir, d))]
if not run_base_dirs:
    print(f"Could not find a run_base_* directory in {run_dir}.")
    print(f"WARNING: You must generate the run directories first by running:")
    print(f"  runcpu --config=spec-ir2 --action=setup --size=test {args.benchmark}")
    sys.exit(1)

target_run_dir = os.path.join(run_dir, run_base_dirs[0])
cmd_file = os.path.join(target_run_dir, "speccmds.cmd")

if not os.path.exists(cmd_file):
    print(f"Could not find speccmds.cmd in {target_run_dir}.")
    sys.exit(1)

exe_path = ""
options = ""
stdin_file = ""

# Parse speccmds.cmd for execution arguments
# The format of the execution line is:
#   -o out -e err echo "../path/exe_base.mytest-m64 arg1 arg2 " > run.sh ; $BIND bash run.sh
# We extract the content inside the double quotes after 'echo'.
with open(cmd_file, "r") as f:
    for line in f:
        line = line.strip()
        # Find lines containing the echo pattern with the executable
        match = re.search(r'echo\s+"([^"]+)"', line)
        if match and "_base." in match.group(1):
            inner = match.group(1).strip()
            parts = inner.split()
            # parts[0] is the executable path, rest are arguments
            base_name = os.path.basename(parts[0])
            clean_name = base_name.rsplit('.', 1)[0] + ".mytest-m64"
            exe_path = os.path.join(bench_path, "exe", clean_name)
            options = " ".join(parts[1:])
            
            # Check for stdin redirect in the speccmds flags before the echo
            stdin_match = re.search(r'-i\s+(\S+)', line.split('echo')[0])
            if stdin_match:
                stdin_file = stdin_match.group(1)
            break

if not exe_path:
    print("Could not parse the executable from speccmds.cmd.")
    sys.exit(1)

if args.cmd_override:
    exe_path = os.path.abspath(args.cmd_override)

# Construct the gem5 launch command
out_dir = os.path.join(os.getcwd(), f"m5out_{os.path.basename(exe_path)}")
cmd = [gem5_opt, "-d", out_dir]

if args.bp_type:
    wrapper_path = os.path.join(gem5_dir, "configs", "example", "se_wrapper.py")
    cmd.extend([wrapper_path, se_py, args.bp_type])
else:
    cmd.append(se_py)

cmd.extend([
    "--cpu-type", args.cpu_type,
    "--caches",
    "--mem-size", "8GB",
    "--cmd", exe_path
])

if options:
    cmd.append(f"--options={options}")

if stdin_file:
    cmd.extend(["--input", stdin_file])

# Add the parsed instruction count parameters for gem5 se.py
if args.warmup_insts:
    cmd.extend(["--warmup-insts", args.warmup_insts])
if args.maxinsts:
    cmd.extend(["--maxinsts", args.maxinsts])
if args.fast_forward:
    cmd.extend(["--fast-forward", args.fast_forward])

cmd.extend(unknown_args)

print(f"[{args.benchmark}] Executing inside: {target_run_dir}")
print(f"[{args.benchmark}] Running command: " + " ".join(cmd))

# Set up environment so gem5 can find its config modules from any cwd
env = os.environ.copy()
env["M5_PATH"] = gem5_dir
configs_path = os.path.join(gem5_dir, "configs")
existing = env.get("PYTHONPATH", "")
env["PYTHONPATH"] = configs_path + (":" + existing if existing else "")

# Execute within the run directory so SPEC finds its input files
subprocess.check_call(cmd, cwd=target_run_dir, env=env)
